### ISSUE TITLE
enum option type 

### ISSUE THREAD

**Issue by Wytamma** [Wytamma/snk#30]
Add an annotation type that allows you to set [enums](https://typer.tiangolo.com/tutorial/parameter-types/enum/).  

config.yaml
```yaml
# Sequencing technology
# [illumina, ont, pgm]
technology: illumina
```

.snk
```yaml
annotations:
  technology: 
    type: Enum[str]
    enums: [illumina, ont, pgm]
```
